apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-scheduler
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 33.2.0
    chart: kube-prometheus-stack-33.2.0
    heritage: Helm
    jobLabel: kube-scheduler
    release: prometheus-stack
  name: prometheus-stack-kube-prom-kube-scheduler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10259
    protocol: TCP
    targetPort: 10259
  selector:
    component: kube-scheduler
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-controller-manager
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 33.2.0
    chart: kube-prometheus-stack-33.2.0
    heritage: Helm
    jobLabel: kube-controller-manager
    release: prometheus-stack
  name: prometheus-stack-kube-prom-kube-controller-manager
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10257
    protocol: TCP
    targetPort: 10257
  selector:
    component: kube-controller-manager
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-proxy
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 33.2.0
    chart: kube-prometheus-stack-33.2.0
    heritage: Helm
    jobLabel: kube-proxy
    release: prometheus-stack
  name: prometheus-stack-kube-prom-kube-proxy
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  selector:
    k8s-app: kube-proxy
  type: ClusterIP
