apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.installScope "cluster" }}
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-networkfirewall-controller
{{ else }}
kind: Role
metadata:
  creationTimestamp: null
  name: ack-networkfirewall-controller
  namespace: {{ .Release.Namespace }}
{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - firewallpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - firewallpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - firewalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - firewalls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - rulegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - rulegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
