---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-networkfirewall-writer
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - firewalls

  - firewallpolicies

  - rulegroups

  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - firewalls
  - firewallpolicies
  - rulegroups
  verbs:
  - get
  - patch
  - update
