---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-networkfirewall-reader
  namespace: default
rules:
- apiGroups:
  - networkfirewall.services.k8s.aws
  resources:
  - firewalls
  - firewallpolicies
  - rulegroups
  verbs:
  - get
  - list
  - watch
