//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionDefinition) DeepCopyInto(out *ActionDefinition) {
	*out = *in
	if in.PublishMetricAction != nil {
		in, out := &in.PublishMetricAction, &out.PublishMetricAction
		*out = new(PublishMetricAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionDefinition.
func (in *ActionDefinition) DeepCopy() *ActionDefinition {
	if in == nil {
		return nil
	}
	out := new(ActionDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Address) DeepCopyInto(out *Address) {
	*out = *in
	if in.AddressDefinition != nil {
		in, out := &in.AddressDefinition, &out.AddressDefinition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Address.
func (in *Address) DeepCopy() *Address {
	if in == nil {
		return nil
	}
	out := new(Address)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Attachment) DeepCopyInto(out *Attachment) {
	*out = *in
	if in.EndpointID != nil {
		in, out := &in.EndpointID, &out.EndpointID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Attachment.
func (in *Attachment) DeepCopy() *Attachment {
	if in == nil {
		return nil
	}
	out := new(Attachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAction) DeepCopyInto(out *CustomAction) {
	*out = *in
	if in.ActionDefinition != nil {
		in, out := &in.ActionDefinition, &out.ActionDefinition
		*out = new(ActionDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.ActionName != nil {
		in, out := &in.ActionName, &out.ActionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAction.
func (in *CustomAction) DeepCopy() *CustomAction {
	if in == nil {
		return nil
	}
	out := new(CustomAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dimension) DeepCopyInto(out *Dimension) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dimension.
func (in *Dimension) DeepCopy() *Dimension {
	if in == nil {
		return nil
	}
	out := new(Dimension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Firewall) DeepCopyInto(out *Firewall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Firewall.
func (in *Firewall) DeepCopy() *Firewall {
	if in == nil {
		return nil
	}
	out := new(Firewall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Firewall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallList) DeepCopyInto(out *FirewallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Firewall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallList.
func (in *FirewallList) DeepCopy() *FirewallList {
	if in == nil {
		return nil
	}
	out := new(FirewallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirewallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallMetadata) DeepCopyInto(out *FirewallMetadata) {
	*out = *in
	if in.FirewallARN != nil {
		in, out := &in.FirewallARN, &out.FirewallARN
		*out = new(string)
		**out = **in
	}
	if in.FirewallName != nil {
		in, out := &in.FirewallName, &out.FirewallName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallMetadata.
func (in *FirewallMetadata) DeepCopy() *FirewallMetadata {
	if in == nil {
		return nil
	}
	out := new(FirewallMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallPolicy) DeepCopyInto(out *FirewallPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallPolicy.
func (in *FirewallPolicy) DeepCopy() *FirewallPolicy {
	if in == nil {
		return nil
	}
	out := new(FirewallPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirewallPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallPolicyList) DeepCopyInto(out *FirewallPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FirewallPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallPolicyList.
func (in *FirewallPolicyList) DeepCopy() *FirewallPolicyList {
	if in == nil {
		return nil
	}
	out := new(FirewallPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirewallPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallPolicyMetadata) DeepCopyInto(out *FirewallPolicyMetadata) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallPolicyMetadata.
func (in *FirewallPolicyMetadata) DeepCopy() *FirewallPolicyMetadata {
	if in == nil {
		return nil
	}
	out := new(FirewallPolicyMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallPolicyResponse) DeepCopyInto(out *FirewallPolicyResponse) {
	*out = *in
	if in.ConsumedStatefulRuleCapacity != nil {
		in, out := &in.ConsumedStatefulRuleCapacity, &out.ConsumedStatefulRuleCapacity
		*out = new(int64)
		**out = **in
	}
	if in.ConsumedStatelessRuleCapacity != nil {
		in, out := &in.ConsumedStatelessRuleCapacity, &out.ConsumedStatelessRuleCapacity
		*out = new(int64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FirewallPolicyARN != nil {
		in, out := &in.FirewallPolicyARN, &out.FirewallPolicyARN
		*out = new(string)
		**out = **in
	}
	if in.FirewallPolicyID != nil {
		in, out := &in.FirewallPolicyID, &out.FirewallPolicyID
		*out = new(string)
		**out = **in
	}
	if in.FirewallPolicyName != nil {
		in, out := &in.FirewallPolicyName, &out.FirewallPolicyName
		*out = new(string)
		**out = **in
	}
	if in.FirewallPolicyStatus != nil {
		in, out := &in.FirewallPolicyStatus, &out.FirewallPolicyStatus
		*out = new(string)
		**out = **in
	}
	if in.NumberOfAssociations != nil {
		in, out := &in.NumberOfAssociations, &out.NumberOfAssociations
		*out = new(int64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallPolicyResponse.
func (in *FirewallPolicyResponse) DeepCopy() *FirewallPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(FirewallPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallPolicySpec) DeepCopyInto(out *FirewallPolicySpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.FirewallPolicy != nil {
		in, out := &in.FirewallPolicy, &out.FirewallPolicy
		*out = new(FirewallPolicy_SDK)
		(*in).DeepCopyInto(*out)
	}
	if in.FirewallPolicyName != nil {
		in, out := &in.FirewallPolicyName, &out.FirewallPolicyName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallPolicySpec.
func (in *FirewallPolicySpec) DeepCopy() *FirewallPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FirewallPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallPolicyStatus) DeepCopyInto(out *FirewallPolicyStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.FirewallPolicyResponse != nil {
		in, out := &in.FirewallPolicyResponse, &out.FirewallPolicyResponse
		*out = new(FirewallPolicyResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateToken != nil {
		in, out := &in.UpdateToken, &out.UpdateToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallPolicyStatus.
func (in *FirewallPolicyStatus) DeepCopy() *FirewallPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FirewallPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallPolicy_SDK) DeepCopyInto(out *FirewallPolicy_SDK) {
	*out = *in
	if in.StatefulDefaultActions != nil {
		in, out := &in.StatefulDefaultActions, &out.StatefulDefaultActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.StatefulEngineOptions != nil {
		in, out := &in.StatefulEngineOptions, &out.StatefulEngineOptions
		*out = new(StatefulEngineOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.StatefulRuleGroupReferences != nil {
		in, out := &in.StatefulRuleGroupReferences, &out.StatefulRuleGroupReferences
		*out = make([]*StatefulRuleGroupReference, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StatefulRuleGroupReference)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StatelessCustomActions != nil {
		in, out := &in.StatelessCustomActions, &out.StatelessCustomActions
		*out = make([]*CustomAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CustomAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StatelessDefaultActions != nil {
		in, out := &in.StatelessDefaultActions, &out.StatelessDefaultActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.StatelessFragmentDefaultActions != nil {
		in, out := &in.StatelessFragmentDefaultActions, &out.StatelessFragmentDefaultActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.StatelessRuleGroupReferences != nil {
		in, out := &in.StatelessRuleGroupReferences, &out.StatelessRuleGroupReferences
		*out = make([]*StatelessRuleGroupReference, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StatelessRuleGroupReference)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallPolicy_SDK.
func (in *FirewallPolicy_SDK) DeepCopy() *FirewallPolicy_SDK {
	if in == nil {
		return nil
	}
	out := new(FirewallPolicy_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallSpec) DeepCopyInto(out *FirewallSpec) {
	*out = *in
	if in.DeleteProtection != nil {
		in, out := &in.DeleteProtection, &out.DeleteProtection
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FirewallName != nil {
		in, out := &in.FirewallName, &out.FirewallName
		*out = new(string)
		**out = **in
	}
	if in.FirewallPolicyARN != nil {
		in, out := &in.FirewallPolicyARN, &out.FirewallPolicyARN
		*out = new(string)
		**out = **in
	}
	if in.FirewallPolicyChangeProtection != nil {
		in, out := &in.FirewallPolicyChangeProtection, &out.FirewallPolicyChangeProtection
		*out = new(bool)
		**out = **in
	}
	if in.SubnetChangeProtection != nil {
		in, out := &in.SubnetChangeProtection, &out.SubnetChangeProtection
		*out = new(bool)
		**out = **in
	}
	if in.SubnetMappings != nil {
		in, out := &in.SubnetMappings, &out.SubnetMappings
		*out = make([]*SubnetMapping, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SubnetMapping)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallSpec.
func (in *FirewallSpec) DeepCopy() *FirewallSpec {
	if in == nil {
		return nil
	}
	out := new(FirewallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallStatus) DeepCopyInto(out *FirewallStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Firewall != nil {
		in, out := &in.Firewall, &out.Firewall
		*out = new(Firewall_SDK)
		(*in).DeepCopyInto(*out)
	}
	if in.FirewallStatus != nil {
		in, out := &in.FirewallStatus, &out.FirewallStatus
		*out = new(FirewallStatus_SDK)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallStatus.
func (in *FirewallStatus) DeepCopy() *FirewallStatus {
	if in == nil {
		return nil
	}
	out := new(FirewallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallStatus_SDK) DeepCopyInto(out *FirewallStatus_SDK) {
	*out = *in
	if in.ConfigurationSyncStateSummary != nil {
		in, out := &in.ConfigurationSyncStateSummary, &out.ConfigurationSyncStateSummary
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SyncStates != nil {
		in, out := &in.SyncStates, &out.SyncStates
		*out = make(map[string]*SyncState, len(*in))
		for key, val := range *in {
			var outVal *SyncState
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SyncState)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallStatus_SDK.
func (in *FirewallStatus_SDK) DeepCopy() *FirewallStatus_SDK {
	if in == nil {
		return nil
	}
	out := new(FirewallStatus_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Firewall_SDK) DeepCopyInto(out *Firewall_SDK) {
	*out = *in
	if in.DeleteProtection != nil {
		in, out := &in.DeleteProtection, &out.DeleteProtection
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FirewallARN != nil {
		in, out := &in.FirewallARN, &out.FirewallARN
		*out = new(string)
		**out = **in
	}
	if in.FirewallID != nil {
		in, out := &in.FirewallID, &out.FirewallID
		*out = new(string)
		**out = **in
	}
	if in.FirewallName != nil {
		in, out := &in.FirewallName, &out.FirewallName
		*out = new(string)
		**out = **in
	}
	if in.FirewallPolicyARN != nil {
		in, out := &in.FirewallPolicyARN, &out.FirewallPolicyARN
		*out = new(string)
		**out = **in
	}
	if in.FirewallPolicyChangeProtection != nil {
		in, out := &in.FirewallPolicyChangeProtection, &out.FirewallPolicyChangeProtection
		*out = new(bool)
		**out = **in
	}
	if in.SubnetChangeProtection != nil {
		in, out := &in.SubnetChangeProtection, &out.SubnetChangeProtection
		*out = new(bool)
		**out = **in
	}
	if in.SubnetMappings != nil {
		in, out := &in.SubnetMappings, &out.SubnetMappings
		*out = make([]*SubnetMapping, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SubnetMapping)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Firewall_SDK.
func (in *Firewall_SDK) DeepCopy() *Firewall_SDK {
	if in == nil {
		return nil
	}
	out := new(Firewall_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Header) DeepCopyInto(out *Header) {
	*out = *in
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(string)
		**out = **in
	}
	if in.DestinationPort != nil {
		in, out := &in.DestinationPort, &out.DestinationPort
		*out = new(string)
		**out = **in
	}
	if in.Direction != nil {
		in, out := &in.Direction, &out.Direction
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.SourcePort != nil {
		in, out := &in.SourcePort, &out.SourcePort
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Header.
func (in *Header) DeepCopy() *Header {
	if in == nil {
		return nil
	}
	out := new(Header)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSet) DeepCopyInto(out *IPSet) {
	*out = *in
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSet.
func (in *IPSet) DeepCopy() *IPSet {
	if in == nil {
		return nil
	}
	out := new(IPSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchAttributes) DeepCopyInto(out *MatchAttributes) {
	*out = *in
	if in.DestinationPorts != nil {
		in, out := &in.DestinationPorts, &out.DestinationPorts
		*out = make([]*PortRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PortRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]*Address, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Address)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]*int64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(int64)
				**out = **in
			}
		}
	}
	if in.SourcePorts != nil {
		in, out := &in.SourcePorts, &out.SourcePorts
		*out = make([]*PortRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PortRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]*Address, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Address)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TCPFlags != nil {
		in, out := &in.TCPFlags, &out.TCPFlags
		*out = make([]*TCPFlagField, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TCPFlagField)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchAttributes.
func (in *MatchAttributes) DeepCopy() *MatchAttributes {
	if in == nil {
		return nil
	}
	out := new(MatchAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerObjectStatus) DeepCopyInto(out *PerObjectStatus) {
	*out = *in
	if in.SyncStatus != nil {
		in, out := &in.SyncStatus, &out.SyncStatus
		*out = new(string)
		**out = **in
	}
	if in.UpdateToken != nil {
		in, out := &in.UpdateToken, &out.UpdateToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerObjectStatus.
func (in *PerObjectStatus) DeepCopy() *PerObjectStatus {
	if in == nil {
		return nil
	}
	out := new(PerObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortRange) DeepCopyInto(out *PortRange) {
	*out = *in
	if in.FromPort != nil {
		in, out := &in.FromPort, &out.FromPort
		*out = new(int64)
		**out = **in
	}
	if in.ToPort != nil {
		in, out := &in.ToPort, &out.ToPort
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortRange.
func (in *PortRange) DeepCopy() *PortRange {
	if in == nil {
		return nil
	}
	out := new(PortRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortSet) DeepCopyInto(out *PortSet) {
	*out = *in
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortSet.
func (in *PortSet) DeepCopy() *PortSet {
	if in == nil {
		return nil
	}
	out := new(PortSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishMetricAction) DeepCopyInto(out *PublishMetricAction) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]*Dimension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Dimension)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishMetricAction.
func (in *PublishMetricAction) DeepCopy() *PublishMetricAction {
	if in == nil {
		return nil
	}
	out := new(PublishMetricAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleDefinition) DeepCopyInto(out *RuleDefinition) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MatchAttributes != nil {
		in, out := &in.MatchAttributes, &out.MatchAttributes
		*out = new(MatchAttributes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDefinition.
func (in *RuleDefinition) DeepCopy() *RuleDefinition {
	if in == nil {
		return nil
	}
	out := new(RuleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroup) DeepCopyInto(out *RuleGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroup.
func (in *RuleGroup) DeepCopy() *RuleGroup {
	if in == nil {
		return nil
	}
	out := new(RuleGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupList) DeepCopyInto(out *RuleGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuleGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupList.
func (in *RuleGroupList) DeepCopy() *RuleGroupList {
	if in == nil {
		return nil
	}
	out := new(RuleGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupMetadata) DeepCopyInto(out *RuleGroupMetadata) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupMetadata.
func (in *RuleGroupMetadata) DeepCopy() *RuleGroupMetadata {
	if in == nil {
		return nil
	}
	out := new(RuleGroupMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupResponse) DeepCopyInto(out *RuleGroupResponse) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(int64)
		**out = **in
	}
	if in.ConsumedCapacity != nil {
		in, out := &in.ConsumedCapacity, &out.ConsumedCapacity
		*out = new(int64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.NumberOfAssociations != nil {
		in, out := &in.NumberOfAssociations, &out.NumberOfAssociations
		*out = new(int64)
		**out = **in
	}
	if in.RuleGroupARN != nil {
		in, out := &in.RuleGroupARN, &out.RuleGroupARN
		*out = new(string)
		**out = **in
	}
	if in.RuleGroupID != nil {
		in, out := &in.RuleGroupID, &out.RuleGroupID
		*out = new(string)
		**out = **in
	}
	if in.RuleGroupName != nil {
		in, out := &in.RuleGroupName, &out.RuleGroupName
		*out = new(string)
		**out = **in
	}
	if in.RuleGroupStatus != nil {
		in, out := &in.RuleGroupStatus, &out.RuleGroupStatus
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupResponse.
func (in *RuleGroupResponse) DeepCopy() *RuleGroupResponse {
	if in == nil {
		return nil
	}
	out := new(RuleGroupResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupSpec) DeepCopyInto(out *RuleGroupSpec) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(int64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.RuleGroup != nil {
		in, out := &in.RuleGroup, &out.RuleGroup
		*out = new(RuleGroup_SDK)
		(*in).DeepCopyInto(*out)
	}
	if in.RuleGroupName != nil {
		in, out := &in.RuleGroupName, &out.RuleGroupName
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupSpec.
func (in *RuleGroupSpec) DeepCopy() *RuleGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RuleGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupStatus) DeepCopyInto(out *RuleGroupStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.RuleGroupResponse != nil {
		in, out := &in.RuleGroupResponse, &out.RuleGroupResponse
		*out = new(RuleGroupResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateToken != nil {
		in, out := &in.UpdateToken, &out.UpdateToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupStatus.
func (in *RuleGroupStatus) DeepCopy() *RuleGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RuleGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroup_SDK) DeepCopyInto(out *RuleGroup_SDK) {
	*out = *in
	if in.RuleVariables != nil {
		in, out := &in.RuleVariables, &out.RuleVariables
		*out = new(RuleVariables)
		(*in).DeepCopyInto(*out)
	}
	if in.RulesSource != nil {
		in, out := &in.RulesSource, &out.RulesSource
		*out = new(RulesSource)
		(*in).DeepCopyInto(*out)
	}
	if in.StatefulRuleOptions != nil {
		in, out := &in.StatefulRuleOptions, &out.StatefulRuleOptions
		*out = new(StatefulRuleOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroup_SDK.
func (in *RuleGroup_SDK) DeepCopy() *RuleGroup_SDK {
	if in == nil {
		return nil
	}
	out := new(RuleGroup_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleOption) DeepCopyInto(out *RuleOption) {
	*out = *in
	if in.Keyword != nil {
		in, out := &in.Keyword, &out.Keyword
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleOption.
func (in *RuleOption) DeepCopy() *RuleOption {
	if in == nil {
		return nil
	}
	out := new(RuleOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleVariables) DeepCopyInto(out *RuleVariables) {
	*out = *in
	if in.IPSets != nil {
		in, out := &in.IPSets, &out.IPSets
		*out = make(map[string]*IPSet, len(*in))
		for key, val := range *in {
			var outVal *IPSet
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(IPSet)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.PortSets != nil {
		in, out := &in.PortSets, &out.PortSets
		*out = make(map[string]*PortSet, len(*in))
		for key, val := range *in {
			var outVal *PortSet
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(PortSet)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleVariables.
func (in *RuleVariables) DeepCopy() *RuleVariables {
	if in == nil {
		return nil
	}
	out := new(RuleVariables)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesSource) DeepCopyInto(out *RulesSource) {
	*out = *in
	if in.RulesSourceList != nil {
		in, out := &in.RulesSourceList, &out.RulesSourceList
		*out = new(RulesSourceList)
		(*in).DeepCopyInto(*out)
	}
	if in.RulesString != nil {
		in, out := &in.RulesString, &out.RulesString
		*out = new(string)
		**out = **in
	}
	if in.StatefulRules != nil {
		in, out := &in.StatefulRules, &out.StatefulRules
		*out = make([]*StatefulRule, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StatefulRule)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StatelessRulesAndCustomActions != nil {
		in, out := &in.StatelessRulesAndCustomActions, &out.StatelessRulesAndCustomActions
		*out = new(StatelessRulesAndCustomActions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesSource.
func (in *RulesSource) DeepCopy() *RulesSource {
	if in == nil {
		return nil
	}
	out := new(RulesSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesSourceList) DeepCopyInto(out *RulesSourceList) {
	*out = *in
	if in.GeneratedRulesType != nil {
		in, out := &in.GeneratedRulesType, &out.GeneratedRulesType
		*out = new(string)
		**out = **in
	}
	if in.TargetTypes != nil {
		in, out := &in.TargetTypes, &out.TargetTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesSourceList.
func (in *RulesSourceList) DeepCopy() *RulesSourceList {
	if in == nil {
		return nil
	}
	out := new(RulesSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulEngineOptions) DeepCopyInto(out *StatefulEngineOptions) {
	*out = *in
	if in.RuleOrder != nil {
		in, out := &in.RuleOrder, &out.RuleOrder
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulEngineOptions.
func (in *StatefulEngineOptions) DeepCopy() *StatefulEngineOptions {
	if in == nil {
		return nil
	}
	out := new(StatefulEngineOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulRule) DeepCopyInto(out *StatefulRule) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(Header)
		(*in).DeepCopyInto(*out)
	}
	if in.RuleOptions != nil {
		in, out := &in.RuleOptions, &out.RuleOptions
		*out = make([]*RuleOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RuleOption)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulRule.
func (in *StatefulRule) DeepCopy() *StatefulRule {
	if in == nil {
		return nil
	}
	out := new(StatefulRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulRuleGroupOverride) DeepCopyInto(out *StatefulRuleGroupOverride) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulRuleGroupOverride.
func (in *StatefulRuleGroupOverride) DeepCopy() *StatefulRuleGroupOverride {
	if in == nil {
		return nil
	}
	out := new(StatefulRuleGroupOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulRuleGroupReference) DeepCopyInto(out *StatefulRuleGroupReference) {
	*out = *in
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = new(StatefulRuleGroupOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int64)
		**out = **in
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulRuleGroupReference.
func (in *StatefulRuleGroupReference) DeepCopy() *StatefulRuleGroupReference {
	if in == nil {
		return nil
	}
	out := new(StatefulRuleGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulRuleOptions) DeepCopyInto(out *StatefulRuleOptions) {
	*out = *in
	if in.RuleOrder != nil {
		in, out := &in.RuleOrder, &out.RuleOrder
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulRuleOptions.
func (in *StatefulRuleOptions) DeepCopy() *StatefulRuleOptions {
	if in == nil {
		return nil
	}
	out := new(StatefulRuleOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatelessRule) DeepCopyInto(out *StatelessRule) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int64)
		**out = **in
	}
	if in.RuleDefinition != nil {
		in, out := &in.RuleDefinition, &out.RuleDefinition
		*out = new(RuleDefinition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatelessRule.
func (in *StatelessRule) DeepCopy() *StatelessRule {
	if in == nil {
		return nil
	}
	out := new(StatelessRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatelessRuleGroupReference) DeepCopyInto(out *StatelessRuleGroupReference) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int64)
		**out = **in
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatelessRuleGroupReference.
func (in *StatelessRuleGroupReference) DeepCopy() *StatelessRuleGroupReference {
	if in == nil {
		return nil
	}
	out := new(StatelessRuleGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatelessRulesAndCustomActions) DeepCopyInto(out *StatelessRulesAndCustomActions) {
	*out = *in
	if in.CustomActions != nil {
		in, out := &in.CustomActions, &out.CustomActions
		*out = make([]*CustomAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CustomAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StatelessRules != nil {
		in, out := &in.StatelessRules, &out.StatelessRules
		*out = make([]*StatelessRule, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StatelessRule)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatelessRulesAndCustomActions.
func (in *StatelessRulesAndCustomActions) DeepCopy() *StatelessRulesAndCustomActions {
	if in == nil {
		return nil
	}
	out := new(StatelessRulesAndCustomActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetMapping) DeepCopyInto(out *SubnetMapping) {
	*out = *in
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetMapping.
func (in *SubnetMapping) DeepCopy() *SubnetMapping {
	if in == nil {
		return nil
	}
	out := new(SubnetMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncState) DeepCopyInto(out *SyncState) {
	*out = *in
	if in.Attachment != nil {
		in, out := &in.Attachment, &out.Attachment
		*out = new(Attachment)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]*PerObjectStatus, len(*in))
		for key, val := range *in {
			var outVal *PerObjectStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(PerObjectStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncState.
func (in *SyncState) DeepCopy() *SyncState {
	if in == nil {
		return nil
	}
	out := new(SyncState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPFlagField) DeepCopyInto(out *TCPFlagField) {
	*out = *in
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Masks != nil {
		in, out := &in.Masks, &out.Masks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPFlagField.
func (in *TCPFlagField) DeepCopy() *TCPFlagField {
	if in == nil {
		return nil
	}
	out := new(TCPFlagField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}
